### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'y'

### ISSUE THREAD

**Issue by jsteward2930** [microsoft/evodiff#11]
Hello, I was interested in learning how to use evodiff and have been encountering an error when running the example code. When I run: 

tokeinzed_sample, generated_sequence  = generate_query_oadm_msa_simple(path_to_msa, model, tokenizer, n_sequences, seq_length, device='cpu', selection_type=selection_type)

I get this error in Jupyter notebooks: 

TypeError                                 Traceback (most recent call last)
Cell In[7], line 10
      6 seq_length=256 
      7 selection_type='random' 
---> 10 tokeinzed_sample, generated_sequence  = generate_query_oadm_msa_simple(path_to_msa, model, tokenizer, n_sequences, seq_length, device='cpu', selection_type=selection_type)

TypeError: forward() missing 1 required positional argument: 'y'

Since forward() isn't in the example code, I figured it may be an issue with another function or method

**Comment by sarahalamdari** [comment]
Can you provide the inputs you are using for the call to generate_query_oadm_msa_simple, so I can help debug?

**Comment by yangkky** [comment]
@jsteward2930 Do you have an update or more details? Otherwise I would like to close this.
