### ISSUE TITLE
Missing uniref50_aa_ref_test.csv

### ISSUE THREAD

**Issue by andrew0901** [microsoft/evodiff#12]
Hi,
I successfully generated sequences for the unconditional situation. However, at the end as main() tried to call aa_reconstruction_parity_plot() (line 148 in evodiff/generate.py) to plot the reconstruction parity, the reference file seems to be missing, giving:

FileNotFoundError: [Errno 2] No such file or directory: '/wynton/home/rotation/fhy/Desktop/DMs/ref/uniref50_aa_ref_test.csv'

I'm wondering where am I supposed to find the file, or is there anything I did wrong?

**Comment by sarahalamdari** [comment]
Hi! I've added this file to data/ in a recent push. 

Nothing is wrong, this file just contains the pre-computed counts of each AA in the test set.

**Comment by yangkky** [comment]
Thanks @andrew0901 for pointing this out, and @sarahalamdari for the PR. 

Fixed by PR #13
