### ISSUE TITLE
Inpaint VS Scaffold

### ISSUE THREAD

**Issue by PodevynLoris** [microsoft/evodiff#14]
If I was to sample a sequence with as scaffold length of 1. 
Considering let's say 3 motives to scaffold, e.g : GDHJK#############HDJKSZ#######HDDD
Would there be a difference with inpainting ?

**Comment by sarahalamdari** [comment]
There is no difference in the inpainting or scaffolding task at inference time. 

We differentiate between the two in the paper for the purpose of downstream application and evaluations
