### ISSUE TITLE
Question about fine-tuning 

### ISSUE THREAD

**Issue by PodevynLoris** [microsoft/evodiff#18]
Hello people, 

I have been struggling to train the 38M parameters model on a fasta dataset from the RCSB. 
I had to alter the dataloader, but when running the script, it leads to batch size issues.
Did anybody try to re-train their models on its own data ? 

Thanks in advance for any of your insight.

Best,

Lo

**Comment by JiangLab2020** [comment]
May I ask how you implement fine-tuning?
