### ISSUE TITLE
Error Loading State Dictionary in ByteNetLMTime: Unexpected Keys

### ISSUE THREAD

**Issue by PodevynLoris** [microsoft/evodiff#25]
I'm encountering an error when trying to load the state dictionary for the ByteNetLMTime model using the provided checkpoint. I'm following the instructions to retrain 38M oadm model on a data formatted as the  uniref50 one with the respective configuration provided in the repository. However, the loading process fails with an error related to unexpected keys in the state dictionary.
Command : 
`python train.py config38M.json --dataset uniref50 -sd checkpoint_input/oaar-38M.tar`
Output and Error : 
`nr 0 gpus 1 gpu 0 rank 0`
`Using 30 as padding index`
`Using 28 as masking index`
`Loading weights from /checkpoint_input/oaar-38M.tar...`
`..............`
`RuntimeError: Error(s) in loading state_dict for ByteNetLMTime: Unexpected key(s) in state_dict: "last_norm.weight", "last_norm.bias". `

**Expected Behavior:**
The model should load the state dictionary without any issues, especially since I am using the provided configuration and checkpoint.
Could you please help in resolving this issue or suggest any necessary steps I might be missing?

**Comment by PodevynLoris** [comment]
I am using a different pytorch version : v1.13.1 , may it be due to this ? 
When printing the checkpoint, the last two layers at not recognised by the model 
`Keys in checkpoint: dict_keys(['step', 'tokens', 'model_state_dict', 'optimizer_state_dict', 'scheduler_state_dict', 'epoch'])
Keys in model's state_dict:
module.embedder.embedder.weight
module.embedder.up_embedder.conv.weight
module.embedder.up_embedder.conv.bias
module.embedder.layers.0.conv.weight
module.embedder.layers.0.conv.bias
module.embedder.layers.0.sequence1.0.weight
module.embedder.layers.0.sequence1.0.bias
module.embedder.layers.0.sequence1.2.conv.weight
module.embedder.layers.0.sequence1.2.conv.bias
module.embedder.layers.0.sequence1.3.weight
module.embedder.layers.0.sequence1.3.bias
module.embedder.layers.0.sequence2.0.weight
module.embedder.layers.0.sequence2.0.bias
module.embedder.layers.0.sequence2.2.conv.weight
module.embedder.layers.0.sequence2.2.conv.bias
module.embedder.layers.1.conv.weight
module.embedder.layers.1.conv.bias
module.embedder.layers.1.sequence1.0.weight
module.embedder.layers.1.sequence1.0.bias
module.embedder.layers.1.sequence1.2.conv.weight
module.embedder.layers.1.sequence1.2.conv.bias
module.embedder.layers.1.sequence1.3.weight
module.embedder.layers.1.sequence1.3.bias
module.embedder.layers.1.sequence2.0.weight
module.embedder.layers.1.sequence2.0.bias
module.embedder.layers.1.sequence2.2.conv.weight
module.embedder.layers.1.sequence2.2.conv.bias
module.embedder.layers.2.conv.weight
module.embedder.layers.2.conv.bias
module.embedder.layers.2.sequence1.0.weight
module.embedder.layers.2.sequence1.0.bias
module.embedder.layers.2.sequence1.2.conv.weight
module.embedder.layers.2.sequence1.2.conv.bias
module.embedder.layers.2.sequence1.3.weight
module.embedder.layers.2.sequence1.3.bias
module.embedder.layers.2.sequence2.0.weight
module.embedder.layers.2.sequence2.0.bias
module.embedder.layers.2.sequence2.2.conv.weight
module.embedder.layers.2.sequence2.2.conv.bias
module.embedder.layers.3.conv.weight
module.embedder.layers.3.conv.bias
module.embedder.layers.3.sequence1.0.weight
module.embedder.layers.3.sequence1.0.bias
module.embedder.layers.3.sequence1.2.conv.weight
module.embedder.layers.3.sequence1.2.conv.bias
module.embedder.layers.3.sequence1.3.weight
module.embedder.layers.3.sequence1.3.bias
module.embedder.layers.3.sequence2.0.weight
module.embedder.layers.3.sequence2.0.bias
module.embedder.layers.3.sequence2.2.conv.weight
module.embedder.layers.3.sequence2.2.conv.bias
module.embedder.layers.4.conv.weight
module.embedder.layers.4.conv.bias
module.embedder.layers.4.sequence1.0.weight
module.embedder.layers.4.sequence1.0.bias
module.embedder.layers.4.sequence1.2.conv.weight
module.embedder.layers.4.sequence1.2.conv.bias
module.embedder.layers.4.sequence1.3.weight
module.embedder.layers.4.sequence1.3.bias
module.embedder.layers.4.sequence2.0.weight
module.embedder.layers.4.sequence2.0.bias
module.embedder.layers.4.sequence2.2.conv.weight
module.embedder.layers.4.sequence2.2.conv.bias
module.embedder.layers.5.conv.weight
module.embedder.layers.5.conv.bias
module.embedder.layers.5.sequence1.0.weight
module.embedder.layers.5.sequence1.0.bias
module.embedder.layers.5.sequence1.2.conv.weight
module.embedder.layers.5.sequence1.2.conv.bias
module.embedder.layers.5.sequence1.3.weight
module.embedder.layers.5.sequence1.3.bias
module.embedder.layers.5.sequence2.0.weight
module.embedder.layers.5.sequence2.0.bias
module.embedder.layers.5.sequence2.2.conv.weight
module.embedder.layers.5.sequence2.2.conv.bias
module.embedder.layers.6.conv.weight
module.embedder.layers.6.conv.bias
module.embedder.layers.6.sequence1.0.weight
module.embedder.layers.6.sequence1.0.bias
module.embedder.layers.6.sequence1.2.conv.weight
module.embedder.layers.6.sequence1.2.conv.bias
module.embedder.layers.6.sequence1.3.weight
module.embedder.layers.6.sequence1.3.bias
module.embedder.layers.6.sequence2.0.weight
module.embedder.layers.6.sequence2.0.bias
module.embedder.layers.6.sequence2.2.conv.weight
module.embedder.layers.6.sequence2.2.conv.bias
module.embedder.layers.7.conv.weight
module.embedder.layers.7.conv.bias
module.embedder.layers.7.sequence1.0.weight
module.embedder.layers.7.sequence1.0.bias
module.embedder.layers.7.sequence1.2.conv.weight
module.embedder.layers.7.sequence1.2.conv.bias
module.embedder.layers.7.sequence1.3.weight
module.embedder.layers.7.sequence1.3.bias
module.embedder.layers.7.sequence2.0.weight
module.embedder.layers.7.sequence2.0.bias
module.embedder.layers.7.sequence2.2.conv.weight
module.embedder.layers.7.sequence2.2.conv.bias
module.embedder.layers.8.conv.weight
module.embedder.layers.8.conv.bias
module.embedder.layers.8.sequence1.0.weight
module.embedder.layers.8.sequence1.0.bias
module.embedder.layers.8.sequence1.2.conv.weight
module.embedder.layers.8.sequence1.2.conv.bias
module.embedder.layers.8.sequence1.3.weight
module.embedder.layers.8.sequence1.3.bias
module.embedder.layers.8.sequence2.0.weight
module.embedder.layers.8.sequence2.0.bias
module.embedder.layers.8.sequence2.2.conv.weight
module.embedder.layers.8.sequence2.2.conv.bias
module.embedder.layers.9.conv.weight
module.embedder.layers.9.conv.bias
module.embedder.layers.9.sequence1.0.weight
module.embedder.layers.9.sequence1.0.bias
module.embedder.layers.9.sequence1.2.conv.weight
module.embedder.layers.9.sequence1.2.conv.bias
module.embedder.layers.9.sequence1.3.weight
module.embedder.layers.9.sequence1.3.bias
module.embedder.layers.9.sequence2.0.weight
module.embedder.layers.9.sequence2.0.bias
module.embedder.layers.9.sequence2.2.conv.weight
module.embedder.layers.9.sequence2.2.conv.bias
module.embedder.layers.10.conv.weight
module.embedder.layers.10.conv.bias
module.embedder.layers.10.sequence1.0.weight
module.embedder.layers.10.sequence1.0.bias
module.embedder.layers.10.sequence1.2.conv.weight
module.embedder.layers.10.sequence1.2.conv.bias
module.embedder.layers.10.sequence1.3.weight
module.embedder.layers.10.sequence1.3.bias
module.embedder.layers.10.sequence2.0.weight
module.embedder.layers.10.sequence2.0.bias
module.embedder.layers.10.sequence2.2.conv.weight
module.embedder.layers.10.sequence2.2.conv.bias
module.embedder.layers.11.conv.weight
module.embedder.layers.11.conv.bias
module.embedder.layers.11.sequence1.0.weight
module.embedder.layers.11.sequence1.0.bias
module.embedder.layers.11.sequence1.2.conv.weight
module.embedder.layers.11.sequence1.2.conv.bias
module.embedder.layers.11.sequence1.3.weight
module.embedder.layers.11.sequence1.3.bias
module.embedder.layers.11.sequence2.0.weight
module.embedder.layers.11.sequence2.0.bias
module.embedder.layers.11.sequence2.2.conv.weight
module.embedder.layers.11.sequence2.2.conv.bias
module.embedder.layers.12.conv.weight
module.embedder.layers.12.conv.bias
module.embedder.layers.12.sequence1.0.weight
module.embedder.layers.12.sequence1.0.bias
module.embedder.layers.12.sequence1.2.conv.weight
module.embedder.layers.12.sequence1.2.conv.bias
module.embedder.layers.12.sequence1.3.weight
module.embedder.layers.12.sequence1.3.bias
module.embedder.layers.12.sequence2.0.weight
module.embedder.layers.12.sequence2.0.bias
module.embedder.layers.12.sequence2.2.conv.weight
module.embedder.layers.12.sequence2.2.conv.bias
module.embedder.layers.13.conv.weight
module.embedder.layers.13.conv.bias
module.embedder.layers.13.sequence1.0.weight
module.embedder.layers.13.sequence1.0.bias
module.embedder.layers.13.sequence1.2.conv.weight
module.embedder.layers.13.sequence1.2.conv.bias
module.embedder.layers.13.sequence1.3.weight
module.embedder.layers.13.sequence1.3.bias
module.embedder.layers.13.sequence2.0.weight
module.embedder.layers.13.sequence2.0.bias
module.embedder.layers.13.sequence2.2.conv.weight
module.embedder.layers.13.sequence2.2.conv.bias
module.embedder.layers.14.conv.weight
module.embedder.layers.14.conv.bias
module.embedder.layers.14.sequence1.0.weight
module.embedder.layers.14.sequence1.0.bias
module.embedder.layers.14.sequence1.2.conv.weight
module.embedder.layers.14.sequence1.2.conv.bias
module.embedder.layers.14.sequence1.3.weight
module.embedder.layers.14.sequence1.3.bias
module.embedder.layers.14.sequence2.0.weight
module.embedder.layers.14.sequence2.0.bias
module.embedder.layers.14.sequence2.2.conv.weight
module.embedder.layers.14.sequence2.2.conv.bias
module.embedder.layers.15.conv.weight
module.embedder.layers.15.conv.bias
module.embedder.layers.15.sequence1.0.weight
module.embedder.layers.15.sequence1.0.bias
module.embedder.layers.15.sequence1.2.conv.weight
module.embedder.layers.15.sequence1.2.conv.bias
module.embedder.layers.15.sequence1.3.weight
module.embedder.layers.15.sequence1.3.bias
module.embedder.layers.15.sequence2.0.weight
module.embedder.layers.15.sequence2.0.bias
module.embedder.layers.15.sequence2.2.conv.weight
module.embedder.layers.15.sequence2.2.conv.bias
module.decoder.conv.weight
module.decoder.conv.bias
module.last_norm.weight
module.last_norm.bias
Epoch: 46
Optimizer state dict keys: dict_keys(['state', 'param_groups'])
Step: 1786763
Tokens: 1.0124176548666846e+23`

**Comment by yangkky** [comment]
I think the problem is that the correct architecture for OADM is `ByteNetLM` not `ByteNetLMTime`. @sarahalamdari can you tell why this is happening?

**Comment by PodevynLoris** [comment]
Thank you for your answer, 
Does it mean that the only way to fine-tune the **oaar-38M.tar** model is to change the training script (more specifically this part ? ) 
`model = ByteNetLMTime(n_tokens, d_embed, d_model, n_layers, kernel_size, r,
                      causal=causal, padding_idx=masking_idx, rank=weight_rank, dropout=args.dropout,
                      tie_weights=args.tie_weights, final_ln=args.final_norm, slim=slim, activation=activation,
                      timesteps=diffusion_timesteps)
`

If yes, do you have any script available that was used to get the current weights of the **oaar-38M.tar** checkpoint?

**Comment by sarahalamdari** [comment]
Oh, I see. Apologies, I misunderstood your question. 

This line should work (just missing one flag!) 

`python train.py config38M.json --dataset uniref50 -sd checkpoint_input/oaar-38M.tar --final_norm`

**Comment by PodevynLoris** [comment]
Oh ok should have checked that thank you! 
By the way I was curious to know if you remember what training accuracy you got after training the `oaar-38M.tar` over the 46 epochs ?
