### ISSUE TITLE
Error with IDR inpainting with Evodiff-MSA

### ISSUE THREAD

**Issue by ZhiYeG** [microsoft/evodiff#27]
Hi, 
I try to run script 
`python evodiff/generate-msa.py --model-type msa_oa_dm_maxsub --batch-size 1 --n-sequences 64 --n-sequences 256 --subsampling MaxHamming --start-query`
But it seems couldn't find this file human_idr_alignments/human_protein_alignments.
Also, could put one simple example in evodiff.ipynb for inpainting IDRs with Evodiff-MSA?
Thanks in advance

**Comment by sarahalamdari** [comment]
These have been added in PR #41
