### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by ChenchaoZhao** [microsoft/evodiff#36]
None of the commands or scripts on the Readme can run. Bugs everywhere

**Comment by yangkky** [comment]
Can you specify what commands or scripts you tried to run and the error messages?

**Comment by ChenchaoZhao** [comment]
I tried every command on the Readme each crashed because of a unique bug... are there any unit tests?

**Comment by yangkky** [comment]
It would be much easier to figure out what's going on if you tell us what
any of the errors are.

**Comment by yangkky** [comment]
We can't really do much here without specific errors to try to debug, so I'm closing this issue.
