### ISSUE TITLE
Error while running inpainting task using EvoDiff-seq

### ISSUE THREAD

**Issue by aksingh135** [microsoft/evodiff#38]
I was trying to run the IDR inpainting task and faced some issues:

### Issue 1:

On running the example given on the GitHub: `python evodiff/conditional_generation_msa.py --model-type msa_oa_ar_maxsub --cond-task idr --num-seqs 1 `

**Error:**
Exception: ('Please select either msa_oa_dm_randsub, msa_oa_dm_maxsub, or esm_msa_1b baseline. You selected:', 'msa_oa_ar_maxsub')

Following the error message I changed the model to msa_oa_dm_maxsub:

` python evodiff/conditional_generation_msa.py --model-type msa_oa_dm_maxsub --cond-task idr --num-seqs 1`

**I get the following error:**
KeyError: 'OMA_ID'

### Issue 2:

When trying to run this command: `python evodiff/conditional_generation.py --model-type oa_dm_38M --cond-task idr --num-seqs 1 --pdb 1bcf --start-idxs 20 --end-idxs 50` 

**Error:**
FileNotFoundError: [Errno 2] No such file or directory: 'data/human_idr_alignments/human_idr_boundaries.tsv'

I am aware that the source for the IDR was linked to the Reverse Homology GitHub, but I cannot find the appropriate file there as well. I have gone through all of their [Zenodo repositories](https://zenodo.org/records/5146063) as well. I'd highly appreciate if I can be directed towards, or be given instructions on how to generate the human_idr_boundaries.tsv file as I am not familiar with 'OMA_ID'.

**Comment by sarahalamdari** [comment]
Hi! apologies, I have asked the authors to update the zenodo. In the meantime these files have been added to `data/human_idr/alignments/` in PR #41
