### ISSUE TITLE
Using a novel config file in EvoDiff-MSA

### ISSUE THREAD

**Issue by diossynvax** [microsoft/evodiff#49]
Hello

For EvoDiff-MSA, I'd like to alter the parameters within the config file but within the generate_msa.py script, the config_fpath argument is currently commented out.

Could you tell what alternations would need to be made to the script in order to incorporate a config file with altered parameters?

Best wishes

Matthew

def main():
    parser = argparse.ArgumentParser()
    #parser.add_argument('config_fpath')
    #parser.add_argument('out_fpath', type=str, nargs='?',
    #                    default=os.getenv('AMLT_OUTPUT_DIR', '/tmp') + '/')
    parser.add_argument('-g', '--gpus', default=1, type=int,
                        help='number of gpus per node')
    parser.add_argument('-off', '--offset', default=0, type=int,
                        help='Number of GPU devices to skip.')

**Comment by yangkky** [comment]
Can't you pass it in using the config_fpath argument?

**Comment by diossynvax** [comment]
Thank you for your quick response.

I'm afraid it doesn't seem to recognise it the argument. Could you post an example of how it can be cited within the command line?
