### ISSUE TITLE
Biotite v1.0.0 breaks conditional diffusion functions.

### ISSUE THREAD

**Issue by colbyford** [microsoft/evodiff#51]
As of Biotite version 1.0.0 (https://github.com/biotite-dev/biotite/releases/tag/v1.0.0), the `filter_backbone()` function is deprecated and is now removed.

This causes the following error when running EvoDiff
```
cannot import name 'filter_backbone' from 'biotite.structure'
```

Two options:
- Change all references of `filter_backbone()` to `filter_peptide_backbone()` (the new name of the function)
- Update the environment.yaml file to use a biotite version >=0.4,<1.0.0

**Comment by sarahalamdari** [comment]
Thanks for catching this, Colby! Updated in d543164
